# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

builds:
  - binary: goreleaser-docker
    env:
      - CGO_ENABLED=0
    ldflags:
      - "-s"
      - "-w"
      - "-extldflags '-static'"
      - "-X main.version={{.Version}}"
    goos:
      - linux
    goarch:
      - amd64

dockers_v2:
  - id: goreleaser-docker
    images:
      - "{{.ProjectName}}"
    dockerfile: Dockerfile.goreleaser
    platforms:
      - linux/amd64
